server:
    port: 8082
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost/Amoy
    username: root
    password: rootybw
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用Druid
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
    filters: stat
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 40 #原本是20
    # 配置获取连接等待超时时间，单位毫秒
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 验证数据库连接的查询语句
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
#    useGlobalDataSourceStat: true

  # 404交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
#jackson:
    ##    serialization:
    ##      indent_output: true #返回josn格式化，用来显示？
# OSS相关配置信息
#aliyun:
#  oss:
#    endpoint: oss-cn-shenzhen.aliyuncs.com    # oss对外服务的访问域名
#    accessKeyId: test # 访问身份验证中用到用户标识
#    accessKeySecret: test # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
#    bucketName: amoy-interest-oss # oss的存储空间
#    policy:
#      expire: 300 # 签名有效期(S)
#    maxSize: 10 # 上传文件大小(M)
#    callback: http://localhost:8080/aliyun/oss/callback # 文件上传成功后的回调地址
#    dir:
#      prefix: amoy-interest/images/ # 上传文件夹路径前缀

management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
