server:
    port: 8080
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost/amoy_interest
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#jackson:
    ##    serialization:
    ##      indent_output: true #返回josn格式化，用来显示？
# OSS相关配置信息
#aliyun:
#  oss:
#    endpoint: oss-cn-shenzhen.aliyuncs.com    # oss对外服务的访问域名
#    accessKeyId: test # 访问身份验证中用到用户标识
#    accessKeySecret: test # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
#    bucketName: amoy-interest-oss # oss的存储空间
#    policy:
#      expire: 300 # 签名有效期(S)
#    maxSize: 10 # 上传文件大小(M)
#    callback: http://localhost:8080/aliyun/oss/callback # 文件上传成功后的回调地址
#    dir:
#      prefix: amoy-interest/images/ # 上传文件夹路径前缀

management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
